/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_archivo;

import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BryanMlg
 */
public class vent extends javax.swing.JFrame {

    Lista list = new Lista();
    nodo aux;
    Read_MP3 read = new Read_MP3();
    DefaultTableModel model = new DefaultTableModel();

    int cont = 0;

    public vent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //void mostrar() {
    //  for (int i = 0; i < aux.length; i++) {
    //    System.out.println("ARTISTA " + aux[i].getartista());
    //}
    //}
    public void rut() {

        JFileChooser fc = new JFileChooser();

        fc.setMultiSelectionEnabled(true);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        byte d = (byte) fc.showOpenDialog(null);
        if (d == 0) {
            String ruta = fc.getSelectedFile().toString();
            paths(new File(ruta));

        }
    }

    public void paths(File ruta) {
        for (final File ficheroEntrada : ruta.listFiles()) {
            if (ficheroEntrada.isDirectory()) {
                paths(ficheroEntrada);
            } else {
                if (ficheroEntrada.getName().endsWith("mp3")) {

                    System.out.println("ruta->> " + ficheroEntrada.getAbsolutePath());
                    System.out.println("NOMBRE: " + ficheroEntrada.getName() + " RUTA DEL ARCHIVO: " + ficheroEntrada.getAbsolutePath());
                    read.lectura(ficheroEntrada.getAbsolutePath());

                }

            }
        }
    }

    void reset() {
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        disquera = new javax.swing.JTextField();
        dis = new javax.swing.JLabel();
        artista = new javax.swing.JTextField();
        art = new javax.swing.JLabel();
        album = new javax.swing.JTextField();
        alb = new javax.swing.JLabel();
        año = new javax.swing.JTextField();
        anio = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        gen = new javax.swing.JLabel();
        txtpath = new javax.swing.JTextField();
        path = new javax.swing.JLabel();
        pag_art = new javax.swing.JTextField();
        pgart = new javax.swing.JLabel();
        pag_dis = new javax.swing.JTextField();
        pgdis = new javax.swing.JLabel();
        cargar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        comboartista = new javax.swing.JComboBox<>();
        comboalbum = new javax.swing.JComboBox<>();
        nopis = new javax.swing.JLabel();
        track = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        inf_cancion = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        PLAY = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        PAUSE = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        inf_play = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MP3");
        setResizable(false);

        principal.setBackground(new java.awt.Color(0, 51, 255));
        principal.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/simbolo-de-formato-de-archivo-mp3.png")))); // NOI18N
        principal.setPreferredSize(new java.awt.Dimension(2000, 2000));
        principal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                principalComponentRemoved(evt);
            }
        });

        disquera.setBackground(new java.awt.Color(100, 181, 246));
        disquera.setBorder(null);
        disquera.setSelectionColor(new java.awt.Color(255, 255, 255));
        disquera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disqueraActionPerformed(evt);
            }
        });

        dis.setBackground(new java.awt.Color(255, 255, 255));
        dis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dis.setForeground(new java.awt.Color(255, 255, 255));
        dis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dis.setText("Disquera");
        dis.setToolTipText("");

        artista.setBackground(new java.awt.Color(100, 181, 246));
        artista.setBorder(null);
        artista.setSelectionColor(new java.awt.Color(255, 255, 255));
        artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaActionPerformed(evt);
            }
        });

        art.setBackground(new java.awt.Color(255, 255, 255));
        art.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        art.setForeground(new java.awt.Color(255, 255, 255));
        art.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        art.setText("Artista");

        album.setBackground(new java.awt.Color(100, 181, 246));
        album.setBorder(null);
        album.setSelectionColor(new java.awt.Color(255, 255, 255));
        album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumActionPerformed(evt);
            }
        });

        alb.setBackground(new java.awt.Color(255, 255, 255));
        alb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alb.setForeground(new java.awt.Color(255, 255, 255));
        alb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alb.setText("Album");

        año.setBackground(new java.awt.Color(100, 181, 246));
        año.setBorder(null);
        año.setSelectionColor(new java.awt.Color(255, 255, 255));
        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });

        anio.setBackground(new java.awt.Color(255, 255, 255));
        anio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        anio.setForeground(new java.awt.Color(255, 255, 255));
        anio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anio.setText("Año");

        genero.setBackground(new java.awt.Color(100, 181, 246));
        genero.setBorder(null);
        genero.setSelectionColor(new java.awt.Color(255, 255, 255));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });

        gen.setBackground(new java.awt.Color(255, 255, 255));
        gen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gen.setForeground(new java.awt.Color(255, 255, 255));
        gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gen.setText("Genero");

        txtpath.setBackground(new java.awt.Color(100, 181, 246));
        txtpath.setBorder(null);
        txtpath.setSelectionColor(new java.awt.Color(255, 255, 255));
        txtpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpathActionPerformed(evt);
            }
        });

        path.setBackground(new java.awt.Color(255, 255, 255));
        path.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        path.setForeground(new java.awt.Color(255, 255, 255));
        path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        path.setText("Path");
        path.setToolTipText("");

        pag_art.setBackground(new java.awt.Color(100, 181, 246));
        pag_art.setBorder(null);
        pag_art.setSelectionColor(new java.awt.Color(255, 255, 255));
        pag_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag_artActionPerformed(evt);
            }
        });

        pgart.setBackground(new java.awt.Color(255, 255, 255));
        pgart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgart.setForeground(new java.awt.Color(255, 255, 255));
        pgart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pgart.setText("Pag. Artista");
        pgart.setToolTipText("");

        pag_dis.setBackground(new java.awt.Color(100, 181, 246));
        pag_dis.setBorder(null);
        pag_dis.setSelectionColor(new java.awt.Color(255, 255, 255));
        pag_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pag_disActionPerformed(evt);
            }
        });

        pgdis.setBackground(new java.awt.Color(255, 255, 255));
        pgdis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgdis.setForeground(new java.awt.Color(255, 255, 255));
        pgdis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pgdis.setText("Pag. Disquera");
        pgdis.setToolTipText("");

        cargar.setBackground(new java.awt.Color(26, 35, 126));
        cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cargarMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_add_database_25px_3.png"))); // NOI18N
        cargar.add(jLabel3);
        cargar.add(jLabel9);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CARGAR");
        cargar.add(jLabel20);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Por Canción" }));
        combo.setOpaque(false);
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboMouseEntered(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        comboartista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Por Artista" }));
        comboartista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboartistaActionPerformed(evt);
            }
        });

        comboalbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar Por Álbum" }));
        comboalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboalbumActionPerformed(evt);
            }
        });

        nopis.setBackground(new java.awt.Color(255, 255, 255));
        nopis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nopis.setForeground(new java.awt.Color(255, 255, 255));
        nopis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nopis.setText("No.Pista");
        nopis.setToolTipText("");

        track.setBackground(new java.awt.Color(100, 181, 246));
        track.setBorder(null);
        track.setSelectionColor(new java.awt.Color(255, 255, 255));
        track.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_save_25px.png"))); // NOI18N
        edit.setText("Guardar Edición");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        inf_cancion.setBackground(new java.awt.Color(255, 255, 255));
        inf_cancion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inf_cancion.setForeground(new java.awt.Color(255, 255, 255));
        inf_cancion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");
        nombre.setToolTipText("");

        name.setBackground(new java.awt.Color(100, 181, 246));
        name.setBorder(null);
        name.setSelectionColor(new java.awt.Color(255, 255, 255));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        PLAY.setBackground(new java.awt.Color(100, 181, 246));
        PLAY.setFocusCycleRoot(true);
        PLAY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PLAYMousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_play_26px.png"))); // NOI18N
        PLAY.add(jLabel4);

        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        PLAY.add(exit);

        PAUSE.setBackground(new java.awt.Color(100, 181, 246));
        PAUSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PAUSEMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_pause_26px.png"))); // NOI18N
        PAUSE.add(jLabel8);

        inf_play.setBackground(new java.awt.Color(66, 165, 245));
        inf_play.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inf_play.setForeground(new java.awt.Color(255, 255, 255));
        inf_play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inf_play.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cancion Seleccionada:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_25px.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_25px.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_25px.png"))); // NOI18N

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addComponent(inf_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(principalLayout.createSequentialGroup()
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(art)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(dis)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(disquera, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(alb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(album, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(anio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(125, 125, 125))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(gen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(path))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalLayout.createSequentialGroup()
                                                .addComponent(pgart)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pag_art))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalLayout.createSequentialGroup()
                                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pgdis)
                                                    .addComponent(nopis)
                                                    .addComponent(nombre))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(track, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pag_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(principalLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(principalLayout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(inf_play, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(principalLayout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(edit))))
                                    .addComponent(comboartista, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addComponent(PLAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(PAUSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 29, Short.MAX_VALUE))))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(inf_cancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dis)
                        .addComponent(disquera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(path)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(art)
                    .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pgart)
                    .addComponent(pag_art, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(principalLayout.createSequentialGroup()
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(alb)
                                            .addComponent(album, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pgdis)
                                            .addComponent(pag_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(anio)
                                            .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nopis)
                                            .addComponent(track, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(inf_play, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gen)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombre)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboalbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1))
                                    .addGroup(principalLayout.createSequentialGroup()
                                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(comboartista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(5, 5, 5))))
                            .addGroup(principalLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5)))
                        .addGap(59, 59, 59)
                        .addGroup(principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PLAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PAUSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(principalLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disqueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disqueraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disqueraActionPerformed

    private void artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaActionPerformed

    private void albumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumActionPerformed

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoActionPerformed

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void txtpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpathActionPerformed

    private void pag_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pag_artActionPerformed

    private void pag_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pag_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pag_disActionPerformed

    private void cargarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarMousePressed
        setColor(cargar);
        rut();
        ResetColor(cargar);
        read.mostrar();

        //pone los indices
        //indice por nombre
        if (!read.devolver().esVacia()) {

            nodo aux = read.devolver().getinicio();
            while (aux != null) {

                combo.addItem(aux.getcancion());

                aux = aux.getSiguiente();

            }

        }

        //Indice por artista
        if (!read.devolver().esVacia()) {

            nodo aux = read.devolver().getinicio();
            while (aux != null) {

                comboartista.addItem(aux.getartista());

                aux = aux.getSiguiente();

            }

        }

        //Indice por album
        if (!read.devolver().esVacia()) {

            nodo aux = read.devolver().getinicio();
            while (aux != null) {

                comboalbum.addItem(aux.getalbum());

                aux = aux.getSiguiente();

            }

        }
        JOptionPane.showMessageDialog(null, "Se ha cargado correctamente");
        dis.setVisible(true);
        disquera.setVisible(true);
        art.setVisible(true);
        artista.setVisible(true);
        alb.setVisible(true);
        album.setVisible(true);
        anio.setVisible(true);
        año.setVisible(true);
        gen.setVisible(true);
        genero.setVisible(true);
        path.setVisible(true);
        txtpath.setVisible(true);
        pgart.setVisible(true);
        pag_art.setVisible(true);
        pgdis.setVisible(true);
        pag_dis.setVisible(true);
        nopis.setVisible(true);
        track.setVisible(true);
        nombre.setVisible(true);
        name.setVisible(true);

    }//GEN-LAST:event_cargarMousePressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

        nodo aux = read.devolver().getinicio();
        while (aux != null) {

            if (combo.getSelectedItem() == aux.getcancion()) {

                txtpath.setText(aux.getpath());
                disquera.setText(aux.getdisquera());
                album.setText(aux.getalbum());
                artista.setText(aux.getartista());
                año.setText(aux.getaño());
                genero.setText(aux.getgenero());
                pag_dis.setText(aux.getpagD());
                pag_art.setText(aux.getPagA());
                track.setText(aux.gettrack());
                name.setText(aux.getcancion());
                aux = aux.getSiguiente();

            } else {

                aux = aux.getSiguiente();
            }

        }

        aux = read.devolver().getinicio();


    }//GEN-LAST:event_comboActionPerformed

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked


    }//GEN-LAST:event_comboMouseClicked

    private void comboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseEntered

    }//GEN-LAST:event_comboMouseEntered

    private void comboartistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboartistaActionPerformed

        nodo aux = read.devolver().getinicio();
        while (aux != null) {

            if (comboartista.getSelectedItem() == aux.getartista()) {

                txtpath.setText(aux.getpath());
                disquera.setText(aux.getdisquera());
                album.setText(aux.getalbum());
                artista.setText(aux.getartista());
                año.setText(aux.getaño());
                genero.setText(aux.getgenero());
                pag_dis.setText(aux.getpagD());
                pag_art.setText(aux.getPagA());
                track.setText(aux.gettrack());
                name.setText(aux.getcancion());
                aux = aux.getSiguiente();

            } else {

                aux = aux.getSiguiente();
            }

        }

        aux = read.devolver().getinicio();

    }//GEN-LAST:event_comboartistaActionPerformed

    private void comboalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboalbumActionPerformed

        nodo aux = read.devolver().getinicio();
        while (aux != null) {

            if (comboalbum.getSelectedItem() == aux.getalbum()) {

                txtpath.setText(aux.getpath());
                disquera.setText(aux.getdisquera());
                album.setText(aux.getalbum());
                artista.setText(aux.getartista());
                año.setText(aux.getaño());
                genero.setText(aux.getgenero());
                pag_dis.setText(aux.getpagD());
                pag_art.setText(aux.getPagA());
                track.setText(aux.gettrack());
                name.setText(aux.getcancion());
                aux = aux.getSiguiente();

            } else {

                aux = aux.getSiguiente();
            }

        }

        aux = read.devolver().getinicio();

    }//GEN-LAST:event_comboalbumActionPerformed

    private void trackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void PLAYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PLAYMousePressed
        try {
            inf_play.setText("");
            inf_play.setText(name.getText());
        } catch (Exception ex) {
            Logger.getLogger(vent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PLAYMousePressed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        nodo aux = read.devolver().getinicio();
        String art = artista.getText();
        while (aux != null) {

            if (art == aux.getartista()) {

                aux.setpath(txtpath.getText());
                aux.setdisquera(disquera.getText());
                aux.setalbum(album.getText());
                aux.setartista(artista.getText());
                aux.setaño(año.getText());
                aux.setgenero(genero.getText());
                aux.setpagD(pag_dis.getText());
                aux.setPagA(pag_art.getText());
                aux.settrack(track.getText());

                System.out.println("el nuevo genero es" + aux.getgenero());
                aux = aux.getSiguiente();

            } else {

                aux = aux.getSiguiente();
            }

        }

        aux = read.devolver().getinicio();
    }//GEN-LAST:event_editActionPerformed

    private void PAUSEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAUSEMousePressed
        try {
        } catch (Exception ex) {
            Logger.getLogger(vent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PAUSEMousePressed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void principalComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_principalComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_principalComponentRemoved
    void setColor(JPanel panel) {
        panel.setBackground(new Color(26,35,126));
    }

    void ResetColor(JPanel panel) {
        panel.setBackground(new Color(92,107,192));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAUSE;
    private javax.swing.JPanel PLAY;
    private javax.swing.JLabel alb;
    private javax.swing.JTextField album;
    private javax.swing.JLabel anio;
    private javax.swing.JLabel art;
    private javax.swing.JTextField artista;
    private javax.swing.JTextField año;
    private javax.swing.JPanel cargar;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> comboalbum;
    private javax.swing.JComboBox<String> comboartista;
    private javax.swing.JLabel dis;
    private javax.swing.JTextField disquera;
    private javax.swing.JButton edit;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel gen;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel inf_cancion;
    private javax.swing.JLabel inf_play;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nopis;
    private javax.swing.JTextField pag_art;
    private javax.swing.JTextField pag_dis;
    private javax.swing.JLabel path;
    private javax.swing.JLabel pgart;
    private javax.swing.JLabel pgdis;
    private javax.swing.JPanel principal;
    private javax.swing.JTextField track;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
